### ISSUE TITLE
Seasonal Attendance Function

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/pypuck#12]
This function will make a query to the Attendance API to get the NHL's seasonal and playoff attendance numbers. These number go from the 1975-76 season to the 2018- 19 season.

The main purpose of this function will be to display the NHL seasonal attendance numbers in an Altair chart. The chart to display will depend on how much data is returned.

This is the source: [attendance](https://records.nhl.com/site/api/attendance)

The function should take in 3 arguments: `playoffs`, `regular`, `season`

The `playoffs` and `regular` arguments are of type `boolean` and the `season` argument is of type `str`.

The user must select one of `playoffs` and/or `regular`. They can either send in a season, or leave it blank. If they leave it blank all seasonal data will be displayed. 

For example: `pypuck.attendance(regular=True, playoffs=True, season=None)`

A call like this would return all of the data from the API. The function would then parse it and display it in an appropriate chart (for example a grouped bar chart showing the attendance by year).

To Do for Milestone 1:

- [x] define the function and write the docstring.

**Comment by jnederlo** [comment]
@chuusan Consider adding in another argument for `plot` which would basically either return a dataframe or plot the object. This would make it more consistent with our other functions.

**Comment by chuusan** [comment]
@jnederlo 

I have defined the `attendance` function and added its docstring. The return of my function is a Altair chart. So I am confuse the format of the example in my docstring and return type. Could you please review my code and the docstring? Thanks

**Comment by jnederlo** [comment]
@chuusan I made a few comments on the review. Generally speaking the function definition works. I think it's totally appropriate if we have to make minor changes to the documentation upon coding up the function. We can refine everything at that time if need be.
