### ISSUE TITLE
README

### ISSUE THREAD

**Issue by jnederlo** [UBC-MDS/pypuck#2]

**Comment by jnederlo** [comment]
Similar Python Packages:
- https://github.com/HarryShomer/Hockey-Scraper
- https://github.com/mhostetter/nhl
- https://pypi.org/project/nhlscrapi/

Similar R Packages:
- TBD

**Comment by PolinaRomanchenko** [comment]
- [x] Purpose and Scope edit
- [x] Features update (1 more function)
- [x] Python Ecosystem
- [x] Dependencies update and fix listing
- [x] Usage

**Comment by jnederlo** [comment]
Closed with PR #22 and PR #21
