### ISSUE TITLE
Team_stats function and tests for Milestone 2

### ISSUE THREAD

**Issue by ManishPJoshi** [UBC-MDS/pypuck#25]
This milestone requires that the team_stats function be competed and that there is at least 1 unit test covering at least 2 - 3 edge cases. The requirements are detailed as follows:

 Iteratively code up the function.
 At least 1 unit test.
 The unit test should cover at least 2 - 3 edge cases.
 The test(s) should cover all branches of program flow (i.e. both sides of an if-statement).
 Update the documentation in response to the coding and the tests for any changes.
 Document the test function(s).
 Check the that the code passes the tests.
 Write the test in the pytest module.
I have thought about the possible tests, and some ideas are listed below:

Check that no more and now fewer than 100 results are returned.
Make sure the end_date is at least equal to or grater than the start_date.
Ensure the start_date and end_date are of the appropriate type.
Make sure the start_date and end_date are valid dates to query.
Update the documentation describing what the valid dates are.
Make sure the default values for the current season are appropriate (i.e. if the arguments are left blank).
Check that the function returns a dataframe object.
Check that the API request returns a valid response.
This could either be an assert, and/or a try/catch statement.
Implement a system to handle when bad responses are returned.
Identify why a bad response was made.
Test that the URL is in-fact correctly specified.

**Comment by jnederlo** [comment]
This issue is closed with PR #32
